typography_spectrum: 0.39152956251064225
color:
  brandStrength: 0.3881453683698495
  lightness: 0.9840308157982545
  saturation: 0.013063602679602729
  rhythmicContrast: 0.9090573981985228
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
github: true
opengraph:
  appId: 'http://facebook.com/tattvika'
  type: Fan Page
layout_spectrum: 0.5739003531628353
analytics:
  google: tattvikacare@gmail.com
  facebook: '20557569'
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d3a73f2-c578-49a5-be3f-c19b617fe70b.png
name: TATTVIKA
url: 'http://thegrid.ai/tattvika'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/957aa468-7a1c-47c5-be85-8333dd1cb63a.jpg
title: TATTVIKA
content: []
coverPrefs:
  filter: false
description: Natural Skincare
purpose:
  - type: contact
    url: 'mailto:tattvikacare@gmail.com'
    label: Contact me
  - type: external
    url: 'http://facebook.com/tattvika'
    label: Shop
